### ISSUE TITLE
Chess Query Language

### ISSUE THREAD

**Issue by zunbeltz** [niklasf/python-chess#10]
Hi,

This looks a nice project to play around with the pgn databases. Did you consider to implement the Chess Query Language (www.rbnn.com/cql/)?
You already have some of the building blocks to do it. 
This will allow to make nice searches in the databases.
##

**Comment by niklasf** [comment]
For reference the latest version is available here: http://www.arves.org/arves/index.php/en/endgamestudies/chess-query-language-5.

After 3 years I can say that this is out of scope for python-chess.

The only advantage I see is that it would be the first open implementation of the language (although a much much slower one).

Instead I have asked the authors to release the source code. There's also an option to check back with the SCID authors since they use part of their GPL-licensed PGN parsing code.

**Comment by sshivaji** [comment]
Btw, it's implemented in a new project now -
https://github.com/mcostalba/scoutfish

**Comment by niklasf** [comment]
Yes, I've been following scoutfish. CQL is a much more complex query language, so it's still intresting. Scoutfish has fewer features but is blazingly fast in comparison.
