### ISSUE TITLE
Incorrect san?

### ISSUE THREAD

**Issue by ghl3** [niklasf/python-chess#1002]
As far as I can tell, I've found a big in the game.board().san, where the san string is showing an unexpected result:

```
import chess.pgn
from io import StringIO

# Print the version
print(chess.__version__)

# Create a PGN String
pgn_string = '''
e4 e5
'''

# Create a StringIO object with the PGN data
pgn_file_like = StringIO(pgn_string)

# Read the first game from the PGN "file"
game = chess.pgn.read_game(pgn_file_like)

# Get the mainline (sequence of moves) of the game
mainline = game.mainline_moves()

# Iterate over the first 10 moves and print them in normal chess notation
for i, move in enumerate(mainline):
    # Print the move san
    print(move, game.board().san(move))    
    
# Close the StringIO object
pgn_file_like.close()
```

This code prints:

```
1.9.4
e2e4 e4
e7e5 exe5
```

Shouldn't it be "e5" instead of "exe5"?

**Comment by MarkZH** [comment]
In the line, `print(move, game.board().san(move))`, the `game` variable is still referring to the first move of the game, so the board returned by `game.board()` is unchanged in each loop iteration. You can see this by changing the `print` statement to `print(move, game.board().fen(), game.board().san(move))`. The FEN string will be the same for both moves. The nonsensical `exe5` is printed because `e7e5` is illegal in the starting board position.

You need to advance to the next move using something like `game = game.next()` beneath the `print` statement. Or, you can get the board before the loop with `board = game.board()` and update the board in the loop with `board.push(move)`.
