### ISSUE TITLE
set_fen should return a ValueError if passed a FEN with no king present

### ISSUE THREAD

**Issue by DarraghGriffin** [niklasf/python-chess#25]
The set_fen function will accept the FEN rnb1k1nr/1pp2ppp/8/3p4/5B2/5P2/6P1/4p3 w kq e6 0 1 for example despite the fact that there is no white king on the board.

**Comment by niklasf** [comment]
Hi @DarraghGriffin, this is intended. It allows storing a partial board setup or playing chess variants without a king. The issue came up before (#16).

At the moment the way to go is [board.status()](http://python-chess.readthedocs.org/en/latest/core.html#chess.Board.status):
```
# only does syntactic checks
board.set_fen("rnb1k1nr/1pp2ppp/8/3p4/5B2/5P2/6P1/4p3 w kq e6 0 1")

# this checks there are kings and also a number of other rules
if board.status() != chess.STATUS_VALID:
    print("Errror!")
```

Possible status values are
```
STATUS_VALID = 0
STATUS_NO_WHITE_KING = 1
STATUS_NO_BLACK_KING = 2
STATUS_TOO_MANY_KINGS = 4
STATUS_TOO_MANY_WHITE_PAWNS = 8
STATUS_TOO_MANY_BLACK_PAWNS = 16
STATUS_PAWNS_ON_BACKRANK = 32
STATUS_TOO_MANY_WHITE_PIECES = 64
STATUS_TOO_MANY_BLACK_PIECES = 128
STATUS_BAD_CASTLING_RIGHTS = 256
STATUS_INVALID_EP_SQUARE = 512
STATUS_OPPOSITE_CHECK = 1024
```
and combinations thereof.

Hope this helps.
