### ISSUE TITLE
Why does board.piece_map() return a dictionary with integer keys instead of a list or an array?

### ISSUE THREAD

**Issue by Husky2490** [niklasf/python-chess#312]

**Comment by Mk-Chan** [comment]
Because each piece type is encoded as an integer (1 through 6 on the top on __init__.py). 

The idea is to use it like an enumeration and access it via those identifiers. The encoding is supposed to be abstracted away.

However, in chess engines it's a very common optimization to just make it an array because you never intend to change the encoding. Probably could be done here too though at the cost of some flexibility.

**Comment by niklasf** [comment]
The keys are square indexes.

```
>>> board = chess.Board()
>>> m = board.piece_map()
>>> m[chess.G1]
Piece.from_symbol('N')
```

In a list of all squares many would be empty. Instead here we get to use the dictionary APIs:

```
>>> m[chess.F3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 21
>>> m.get(chess.F3)
None
```

There are various ways to work with these square indexes: https://python-chess.readthedocs.io/en/latest/core.html#squares
