### ISSUE TITLE
len method in SquareSet returns unexpected answer for complemented masks

### ISSUE THREAD

**Issue by hasnul** [niklasf/python-chess#316]
a = chess.SquareSet( ~chess.BB_ALL )
print(a) gives expected board:
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
len(a) yields 1; I expected 0.

b = chess.SquareSet( ~chess.BB_BACKRANKS )
print(b) looks fine:
. . . . . . . .
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
. . . . . . . .

len(b) yields 9; I expected 48

Is it designed to behave like this or is it a bug?

**Comment by niklasf** [comment]
Thanks for reporting. This was already fixed on master (which has a completely rewritten SquareSet), but should have been backported to 0.23.x for a bugfix release. I did that now and published v0.23.10.

The explanation is that internally python-chess takes care that bitboards are never negative, for example by using `chess.BB_ALL & ~chess.BB_BACKRANKS` instead of `~chess.BB_BACKRANKS`. However a convenience API like `SquareSet` should just take care of that.
