### ISSUE TITLE
Problem using syzygy TBs

### ISSUE THREAD

**Issue by oscardssmith** [niklasf/python-chess#321]
The following fails with error 
        board=chess.Board(fen='8/3N4/p3K3/6k1/7Q/8/8/r7 w - - 0 1')
        tb.probe_wdl(board)

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1542, in probe_wdl_table
    table = self.wdl[key]
KeyError: 'KQNvRP'`
This is weird because it is missing the black king even though it exists. Any ideas why? I'm on version .23.9 with python 3.7. This looks pretty similar to #13, but still exists with a newer version.

**Comment by oscardssmith** [comment]
Never mind, slightly invalid FEN (white to move, but black is checked).

**Comment by oscardssmith** [comment]
Ok, now I think I found a real bug. For any 6 man KRRvKRR positions (eg `4R3/1k6/3R4/5r2/8/5r2/2K5/8 w - - 0 1`) I get 

Traceback (most recent call last):
  File "end_game_eval.py", line 90, in main
    true = tb.probe_wdl(board)
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1671, in probe_wdl
    v, _ = self.probe_ab(board, -2, 2)
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1575, in probe_ab
    v = self.probe_wdl_table(board)
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1548, in probe_wdl_table
    return table.probe_wdl_table(board)
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1183, in probe_wdl_table
    self.init_table_wdl()
  File "/usr/local/lib/python3.6/dist-packages/chess/syzygy.py", line 1051, in init_table_wdl
    self.check_magic(self.variant.pawnless_tbw_magic))
AssertionError
I shouldn't be getting any errors here, because I am now using get_wdl(), and the Fen is valid. 
Any ideas why this is happening?

**Comment by niklasf** [comment]
For the first issue: When probing user provided positions it can be helpful to use [`board.is_valid()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.is_valid).

The assertion error would indicate that the tablebase file `KRRvKRR.rtbw` or one of its subtables has a broken header. I'll improve the error message.

Maybe there was an issue with the download? (Of course there might also be a bug, but since it's working for me, please first try to verify the tablebase files. Multiple types of checksums are known, e.g. http://tablebase.sesse.net/syzygy/6-WDL/3-4-5-6.md5).

**Comment by oscardssmith** [comment]
you are right, I had a slightly broken file. An error message improvement would be good. Also shouldn't it return `None` for `get_wdl`?

**Comment by niklasf** [comment]
Good point. Strictly speaking, with the current wording of the documentation, yes. The intent was to get `None` for missing tables, not outright broken ones, disk errors, OS errors, ...

* [ ] Improve error message
* [ ] Adjust docs
