### ISSUE TITLE
[RFC] Higher level engine API

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#339]
The current XBoard and UCI engine APIs are designed to be very close to the underlying protocol. This has some clear advantages:

* Developers who know the protocol know exactly what to expect from the API.
* Everything that is possible to do with the protocol is also possible to do using the API.

Things I don't like about that design:

* If you intend to use both UCI and XBoard engines you need to make two implementations (or use an external adapter).
* Wierd parts of the underlying protocol are exposed, e.g. pondering in UCI, sign of scores.
* Analyzing a position consists of multiple steps (clear hashtables, setup position, search, possibly manually stop). When using the engine asynchronously it is easy to introduce race conditions (discussed a bit on #256, and maybe there is even a race condition in the implementation itself #249).

Tasks a high level engine API would have to support:

* Configure engine options (except `UCI_Chess960`, `UCI_Variant`, `UCI_AnalyseMode`, `MultiPV`, because these can be auomatically managed).
* With time or node limits, optionally skill level, search for the best move in a given position. Optionally start pondering afterwards. XBoard engines can offer or accept draws.
* With time or node limits, optionally MultiPV, analyse a position. Retrieve principal variations and their evaluations.
* Analyze a position forever, optionally MultiPV. Retrieve principal variations and their evaluations at each depth.

Misc status information (nodes per second, hash usage, syzygy hits) can be retrieved by a listener.

Each of these tasks can be cancelled at any time.

Starting a new task could automatically cancel the current task, if any. A wrapper class can be provided that instead queues tasks. Or the other way around.

---

Am I missing some use cases? Thoughts?

cc @LocutusOfPenguin, @Mk-Chan, @gbtami, @ddugovic

**Comment by brianprichardson** [comment]
Just a detail, but XBoard engines can also resign.

**Comment by Mk-Chan** [comment]
No I agree that a higher level API would be useful and in fact that is what GUIs basically provide as buttons and whatnot.

We need to decide how high level we want to go with this. Do we just want a wrapper which abstracts the UCI/XBoard protocol or do we want to abstract out common processes like setup this FEN and search for x time, n nodes, with pondering, etc...?

To make one, I guess we need to identify the common functionalities (board setup, search, options, etc) and first create wrappers anyway.
Certain features of protocols cannot be made available as the protocols are not very similar.
Ideally we'd want to allow the developer to transparently dip into the functionality of the specific protocol which is being used under the hood if required but that would need a "unsafe block" type functionality where at each entry to the API functions, certain constraints must be met (or have the whole API stateless).

**Comment by ddugovic** [comment]
> If you intend to use both UCI and XBoard engines you need to make two implementations (or use an external adapter).

I agree, however perhaps it is not necessary to fully support both CECP/XBoard as well as UCI, if sufficiently good external adapters exist.  Extending either protocol to implement some features of the other seems challenging enough on its own; extending both protocols within the same project seems ambitious.

It may be worth asking developers of XBoard, Cutechess, etc. for engine API ideas (or that might accidentally encourage them to extend protocols and just make the problem harder, I don't know).

**Comment by gbtami** [comment]
PyChess has something like this in [Player](https://github.com/pychess/pychess/blob/master/lib/pychess/Players/Player.py) and [Engine](https://github.com/pychess/pychess/blob/master/lib/pychess/Players/Engine.py) modules. Maybe the design and implementation is not exactly what you want or like, but you can borrow ideas from them.

**Comment by rpdelaney** [comment]
> Analyzing a position consists of multiple steps (clear hashtables, setup position, search, possibly manually stop).

For reasons you might be able to guess, I very much like having this level of granular control. It would be especially disastrous if I lost the ability to decide when the hash table is getting cleared. 

Honestly I found the existing API easy enough to work with once I got the hang of it. If you implement a higher-level API specific to python-chess, I think it would be a good idea to leave the lower-level methods behind.

**Comment by niklasf** [comment]
Just merged the first attempt to master: https://python-chess.readthedocs.io/en/latest/engine.html

I think I adressed all comments, but nothing is set in stone. Feedback/concerns/questions welcome.

**Comment by rpdelaney** [comment]
One thought off the cuff: Since evaluations are always printed to users from the standpoint of white, I'm often calculating who is to move so I can decide whether I need to invert the evaluation before I render it in a comment. Is this something that could be abstracted into the library?

I'll read into this and give more detailed comments later (such as I have them). Thank you for continuing to make this library even better.

**Comment by niklasf** [comment]
Thanks, now 40463cbc25b606787c17f2ce3c6bd4226498b3e6 normalizes scores to White's point of view. An alternative would be attaching the POV to scores as a property, but then I am not sure what would be an intuitive total order to define on that.

**Comment by rpdelaney** [comment]
Hm. I feel bad because I should have been more clear about my ask. This change is possibly going to shift the problem into other parts of my application because I use the score from the POV of the player to move to calculate whether the current move was a mistake or not. So now I will need to check which side played the move to know whether a lower or higher score of the played move vs the bestmove score indicates a mistake, I think. 

Now that I've written that out, maybe I could just do something like `if abs(bestmove_score - playedmove_score) > MISTAKE_THRESHOLD` since we would assume that any change in evaluation from the engine bestmove is in the wrong direction. But I will have to think that through a bit more.

FWIW when I implement the redesign I discussed with you offline this will clean up the logic a lot anyway, since I'll hide this check in my own internal class method. But there could be other consequences I'm not thinking of yet too.

I guess what I'm saying is that 0463cb could have negative consequences for other applications than mine. If there's some clean way of building in another API call that can give the evaluation from the other standpoint (player to move score -or- absolute [white] score) that might be ideal.

**Comment by ddugovic** [comment]
Unless a player is getting two moves in a row, figuring out how to normalize scores to White's POV within other applications should be relatively straightforward.

**Comment by rpdelaney** [comment]
Yes!! Functionally, that is perfect. I'm not completely clear on how it should be called in each case, so I have mild doubts about naming it `PovScore` (it looks like you can get absolute, non-pov scores too); but something like that is very much what I had in mind, since it lets me choose which kind of evaluation I want easily.

**Comment by niklasf** [comment]
And ... included in v0.25.0. Let's make seperate issues for any problems or follow-up discussion.
