### ISSUE TITLE
Python-Chess using IronPython

### ISSUE THREAD

**Issue by rsocor01** [niklasf/python-chess#348]
I have been working for a while on a GUI interface for an electronic chess board. The program is written in vb.net. I would like to use Python-Chess in this program for move validation. It is more reliable than using just Stockfish to validate the moves. Is it possible to read the output from Python-Chess in a vb.net program?

Python-Chess doesn't seem to work with IronPython, or at least it doesn't work for me. Does anybody have any code to implement Python-Chess in vb.net? Has anybody tried this before in C or VB?

Thank you,

Robert

**Comment by niklasf** [comment]
> Python-Chess doesn't seem to work with IronPython, or at least it doesn't work for me.
Hi. Can you please provide details, like the specific error message?

**Comment by rsocor01** [comment]
Hi Niklasf,

Thank you for your response. I can install Python-Chess using Python 3.7.2 without any problems. However, using the IronPython shell I get the following error. 

Has anybody implemented Python-Chess in C or VB using IronPhyton?

Thanks for your help,

Robert

`
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install python-chess
  File "<stdin>", line 1
    pip install python-chess
        ^
SyntaxError: unexpected token 'install'
>>>
`

**Comment by niklasf** [comment]
Ok, thanks. That looks like a Python command prompt, but pip has to be run in the System/Windows command prompt. In principle that seems possible, like so:

http://ironpython.net/blog/2014/12/07/pip-in-ironpython-275.html

However it looks like IronPython does not (yet) support Python 3. So the lastest python-chess would not be compatible. The latest compatible version is `v0.23.10` (some months old, with [several bugfixes](https://github.com/niklasf/python-chess/blob/master/CHANGELOG.rst) since then). You could try to install it like so:

```
ipy -X:Frames -m pip install python-chess==0.23.10
```
(Currently can't try any of this myself).
