### ISSUE TITLE
EPD parsing PV tag

### ISSUE THREAD

**Issue by jordanbray** [niklasf/python-chess#35]
The EPD spec allows the 'PV' tag (principal variation) to contain a list of moves, which could be executed in order.  the Board.set_epd() function fails to do this because it assums there is only one move, and also assumes that the move is to be played in the current position.

**Comment by niklasf** [comment]
Hi @jordanbray and thanks for your pull request!

Since we can not automatically distinguish a set of moves and a stack of moves, maybe we should hardcode this for `pv` and `bm`.

And then have a look what other commonly used tags there are: https://chessprogramming.wikispaces.com/Extended+Position+Description#EPD%20Syntax-Operations-Opcode%20mnemonics.

Stack of moves: `pv`
Set of moves: `am`, `bm`
Single moves: `pm`, `sm` (maybe the default for user defined tags)

On the downside this wouldn't work for user defined tags with move sets or stacks. I haven't seen any others, though ...

Niklas
