### ISSUE TITLE
Insufficient material for a win on time

### ISSUE THREAD

**Issue by bsamseth** [niklasf/python-chess#362]
In a timed game, player `A` may claim a draw even though they have lost on time if player `B` has no conceivable way of winning the game. In the simplest case, if player `B` only has a king, then its clear that even though player `A` runs out of time the game ends in a draw. However, there are some unexpected edge cases. For instance, if player `B` only has a king and knight (normally not sufficient material to win againts a lone king), they may still win the game if player `A` has enough material on the board. This is because you can in theory use `A`'s pieces as part of the mating net, and so if player `A` flags they lose the game in this case.

As far as I can tell, deciding between a win or a draw in such cases is not implemented in python-chess (please correct me if I'm wrong).

[lichess.org](https://lichess.org/) has this feature implemented. For my use case (running timed matches) this feature would be very handy to have. I'm happy to provide a pull request with an implementation of this if you think it would be a good addition.

**Comment by niklasf** [comment]
I agree that this would be useful.

Since this is a hard problem, any implementation (including Lichess's) will be some kind of approximation. It seems important that:

* If `color` can win, we will never say that `color` has insufficient material.

But the converse does not nescessatily hold:

* If `color` cannot win, we hope to detect this in most cases, but might miss some cases that are drawn. (For example the position might be [locked up](https://syzygy-tables.info/?fen=4k3/8/8/1p2p2p/1P2P2P/8/8/4K3_b_-_-_0_1), or a [forced sequence of moves leads to insufficient material](https://syzygy-tables.info/?fen=4k3/4Q3/8/8/8/8/8/4K3_b_-_-_0_1)).

Taking the name literally, how about this?

* Looking only at the material configuration, taking into account if bishops are positioned on dark or light squares, but not concrete piece positions, is there a position with the same material configuration where `color` can win with a series of legal moves. If not, then `color` has insufficient winning material.

I added this as `board.has_insufficient_material(color)` on the master branch. Not yet implemented for variants.

**Comment by bsamseth** [comment]
I was originally thinking what you just implemented, yes. I did not consider the harder cases that you bring up. I think to try to detect every case of locked/forced-draw sequences would, in general, require a search to an arbitrary depth (limited only by the 50 move rule and repetition). So in my mind `board.has_insufficient_material(color)` is the only reasonable solution, and will probably cover the _vast_ majority of cases. As such, I would consider this issue resolved with this addition.

Side note: Thanks for the quick and solid response to this!
