### ISSUE TITLE
simplify subclassing GameNode, Game 

### ISSUE THREAD

**Issue by till314** [niklasf/python-chess#380]
in GameNode.add_variation you explicitly call GameNode() to generate a new node. Could you replace this by something like self.__class__(). Otherwise you have to reimplement the add_variation method each time you subclass GameNode.

(There also are similar minor issues in the accept/accept_subgame methods wrt to 'Game').

Also have you considered to turn the read_game function into a static method for the Game class. Then subclassing would be simpler (now you have to override the begin_game method in the GameCreator class as well in order to create instances of your subclass).

Neither of these issues is really a problem but cutting and pasting code to change just a name or two always makes me uneasy.

**Comment by niklasf** [comment]
`add_variation()` can't quite use `self.__class__`, because it needs to create a `GameNode`, even when called on a `Game` instance. I added a `GameNode.dangling_node()` classmethod in order to create a single point to overwrite.

Still subclassing an existing class hierarchy is quite verbose:
```python
class MyGameNode(chess.pgn.GameNode):
    @classmethod
    def dangling_node(cls):
        return MyGameNode()

class MyGame(chess.pgn.Game, MyGameNode):
    pass
```

If you're doing something that might be commonly useful, maybe it can be added to the library, or maybe there is an alternative way to achieve it?

---

`read_game()` can't really be a static method on `Game`, because creating a game is just a special case. There are all kinds of other visitors that can be used.

However I added an experimental `Game.creator` classmethod that allows doing

```python
chess.pgn.read_game(file, Visitor=MyGame.creator)
```

---

Disclaimer: This is getting quite complex. No guarantee it'll land as is.

**Comment by till314** [comment]
Thanks. I'll give it a try.  It'll still take a while before things are stable enough to publish a first version so changing back and forth is not a problem.

As for the question whether I am "doing something that might be commonly useful", that remains to be seen but the goal is to have a bunch of chess related widgets (I am using pyqt5). One possible application  would be a python-based scid. Others training tools (openings, tactics, endgames). What I have working so far is a basic board (using svg) and a tree based pgn editor. Currently I trying to figure out how to best get the chess engine interface (using asyncio) to work nicely with Qt's eventloop. After that probably some endgame training tool using syzygy tables.

**Comment by gbtami** [comment]
@till314 using https://github.com/harvimt/quamash can be an option to consider.

**Comment by till314** [comment]
Thanks, that's what I am trying but the infinite analysis gets stuck somewhere.

**Comment by niklasf** [comment]
Sounds like an awesome project! Let me know if you find other issues, or if you manage to pin down the infinite analysis bug to a reproducible example.
