### ISSUE TITLE
Trouble using asyncio engine.analysis with qt

### ISSUE THREAD

**Issue by till314** [niklasf/python-chess#395]
I am trying to write a set of qt chess-widgets. For that I want to use your interface to the UCI engines. Using asyncio with qt requires (as far as I know) using the same event-loop for qt and asyncio. I tried using asyncqt and quamash. 

The problem I get stuck on is that after setting the event loop policy any call to get_running_loop always fails. I attach a sample program where you can start and stop a simple async task without problems but the uci engine always fails because of the failing call to get_running_loop.

I had to slightly modify your policy (as shown below) to make the task run

class Policy(chess.engine.EventLoopPolicy):
    def new_event_loop(self):
        return QEventLoop()

Any suggestions (as to where I should look for solutions) would be appreciated.
[qteng.py.txt](https://github.com/niklasf/python-chess/files/3051831/qteng.py.txt)

**Comment by niklasf** [comment]
The `chess.engine.EventLoopPolicy` does two things:

* Windows compability, by returning an event loop capable of running subprocesses. We don't need this when using `QEventLoop`.
* Making the synchronous API work by making child watchers work off the main thread. We don't need this when using the async API.

This means we can remove the policy, and exclude a couple of potential problems.

Next try `asyncio.get_running_loop()` in an `asyncqt.asyncSlot()` or a new task. This fails, and probably means that it's an `asyncqt` bug. `asyncio.get_running_loop()` was introduced recently in Python 3.7, which is why it maybe isn't supported yet.

Meanwhile you could manually do `asyncio.events._set_running_loop(loop)`, which I believe is what `asyncqt` should be doing internally.

**Comment by till314** [comment]
Thanks. The suggestion to use asyncio.events._set_running_loop(loop) was exactly what I needed.
