### ISSUE TITLE
Why doesn't 'board' display a board from a scirpt?

### ISSUE THREAD

**Issue by MagicSpik3** [niklasf/python-chess#439]
Console commands:
>>>import chess
>>>board = chess.Board()
>>>board
 displays a nice board, but running the same lines from a script doesn't.
How can I make a nice animation of my game?

**Comment by niklasf** [comment]
python-chess only implements chess rules and common formats.

Boards are shown in Jupyter-Notebooks because there's some very basic integration using `chess.svg` (https://python-chess.readthedocs.io/en/latest/svg.html).

Terminals generally don't support displaying images. You can use the same module, but you'll have to implement the details yourself. For example you could create SVG files, or use a GUI library to display things.
