### ISSUE TITLE
Pure Python Gaviota tablebase support

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#45]
Implement probing of [Gaviota tablebases](https://github.com/michiguel/Gaviota-Tablebases) in pure Python. (Only) compressed *.gtb.cp4* files need to be handled.

**Comment by niklasf** [comment]
Relevant: https://code.google.com/p/gaviota-probe-dotnet/

**Comment by jnavila** [comment]
Hello, I'm interested in trying to tackle this. I have a few questions:

 *  does porting "as is" the C# matches your expectations?
 * can we use numpy for easy management of arrays?
 * I know almost nothing about chess. Is there something I should know before starting?

Thanks in advance.

**Comment by niklasf** [comment]
Hi. The C# code looks pretty complete to me. For Python we'll want an interface similar to the existing ctypes bindings:

* [probe_dtm(board)](https://github.com/niklasf/python-chess/blob/master/chess/gaviota.py#L83)
* [probe_wdl(board)](https://github.com/niklasf/python-chess/blob/master/chess/gaviota.py#L102)

This is a challenging task, but you don't have to be a chess player to do this. Knowing the basic rules and the concept of tablebases is going to be sufficient. I'd be happy to help if you have any questions.

**Comment by jnavila** [comment]
I just wanted to give you a heads up on the process of porting from cs:

The main container object has been broken apart so that all the tables variables are now at the top level.

Most init function are initializing the variable outside of their scope, I chose to not change the body of these functions except that they return the initialized table. They are called at the top level to initialize the top-level variables.

Most of the code has been ported by:
 * remove type information
 * for loops are pythonized by remove the index and looping directly on the table elements. To do so, the lists are cut to the right size. Initialization loops to invalid values are pythonized in list comprehensions.
 * Transform procedures that change global variables in place to functions that return the changed data. Obviously, the call sites must be changed too.

I expect to have push after and open a pull request after this first pass. The code will be all correct python code but presumably not working. This will be only for review. 

I haven't felt the need to use numpy to replace the loops. That may come in a second pass.

Any remark is welcome.

**Comment by niklasf** [comment]
Sounds good. Glad you're making progress! I can probably give more feedback when I see the specific code.
