### ISSUE TITLE
Info element 'String' from engine.analyse() only shows for first multipv

### ISSUE THREAD

**Issue by CaryKnoop** [niklasf/python-chess#459]
Using Lc0 0.23 the 'String' info element only shows for the first multipv.  This is not the case for engine.analysis(), in this case, all 'String' info elements are provided after all the other 'info' elements at the end.  

I am not sure if this an Lc 0.23 timing issue or a python-chess api issue,

To reproduce
...
engine.configure({'VerboseMoveStats': 'true'})
...
info = engine.analyse(......., multipv=100 .....)

If you pretty print 'info' it only shows the 'String' info string for the first pv.

**Comment by niklasf** [comment]
Can you please include some example engine output, either from the [debug log](https://python-chess.readthedocs.io/en/latest/engine.html#logging) or from directly trying equivalent commands in a console?

**Comment by CaryKnoop** [comment]
Log file and output of 'info' data structure (pretty print)

[engine.analyze.txt](https://github.com/niklasf/python-chess/files/3933148/engine.analyze.txt)
[engine.analysis.txt](https://github.com/niklasf/python-chess/files/3933149/engine.analysis.txt)

**Comment by niklasf** [comment]
Thanks. I see the issue now.

Usually new info updates older one, for example `info depth 20` followed by `info depth 21` results in `{"depth": 21}`. The same is happening for `info string`.

Ideally Lc0 would output `info multipv 1 string`,  `info multipv 2 string` so that the last string for each multipv would be recorded.

Otherwise I don't think this can be fixed without special-casing Lc0.

`analysis()` streams info line by line, so the user can decide how to merge (or not merge) info.
