### ISSUE TITLE
FileNotFoundError  (chess.engine.SimpleEngine.popen_uci('stockfish')

### ISSUE THREAD

**Issue by kapeed7** [niklasf/python-chess#574]
Although the problem is fixed.... (i hope it will help the new users)   :)

I was working previously on the python 3.6.x and had stockfish.exe placed in my system32 folder. it worked like a charm, But since i updated my python to 3.8.3,  that line may be facing permission issues although the command "stockfish" works pretty well in the command line. I tried using absolute path but without any success.

![error](https://user-images.githubusercontent.com/44173997/84650548-19853600-af26-11ea-96ed-81a9df1dafbb.jpg)

So, i cut the file from system32 folder and pasted it in the python root folder or any folder whose path is set in environment variable and now it works.

**Comment by niklasf** [comment]
Thanks.

I have (since) updated the examples in the documentation to `popen_uci("/usr/bin/stockfish")`, showing that a path is expected (unless the executable is in `PATH`, which you achieved by putting it into special directories).

> I tried using absolute path but without any success.

That's wierd. I'll try to investigate whenever I get my hands on a Windows machine ...

**Comment by kapeed7** [comment]
;)
