### ISSUE TITLE
error in pgn docu

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#60]
Hi,
in the docu there is an error:
Thats wrong:
exporter = chess.pgn.StringExporter()
pgn_string = game.accept(exporter, headers=True, variations=True, comments=True)

Thats right:
exporter = chess.pgn.StringExporter(headers=True, variations=True, comments=True)
pgn_string = game.accept(exporter)

Can y say something, why y now have this visitor stuff? Its different (with new api), but i dont see an advantage for the user. I see its cleaner in coding, something else?

**Comment by niklasf** [comment]
Thank you for reporting this! Fixed.

It's indeed mostly just cleaner coding. But there is one more advantage to having a common visitor interface for export and for parsing.

I was going over large PGN files and wanted to look at the positions. Previously there were 3 stages:

```
          read_game()                loop through nodes
PGN file -------------> Game model ----------------------> Result
```

Now you can also directly pass a visitor to [read_game()](https://python-chess.readthedocs.org/en/latest/pgn.html#chess.pgn.read_game).

```
          read_game(Visitor=MyVisitor)
PGN file -------------------------------> Result
```

This can be a lot faster, because no game model has to be created.

---

Practical example: Let's say you want to strip comments from a game and print it to stdout. Before:

```
pgn_file = open("data/pgn/kasparov-deep-blue-1997.pgn", "r")                       
                                                                                   
game = chess.pgn.read_game(pgn_file)                                               
                                                                                   
exporter = FileExporter(sys.stdout)                                                
game.export(exporter, comments=False)
```

After:

```
pgn_file = open("data/pgn/kasparov-deep-blue-1997.pgn", "r")                       
                                                                                   
exporter = FileExporter(sys.stdout, comments=False)                             
chess.pgn.read_game(pgn_file, Visitor=lambda: exporter)
```
