### ISSUE TITLE
Question - Adding NAG.

### ISSUE THREAD

**Issue by CoderAryanAnand** [niklasf/python-chess#665]
Hi Niklas,
Could you please explain how to add NAGs (!!,?, etc) in the pgn (in the mainline) itself based on the engine evaluation of the move.
Thanks,
Aryan

**Comment by niklasf** [comment]
Hi Aryan, there is no ready-made solution, mostly because there isn't a clear definition of the exact meaning or thresholds for these symbols:
* `?` and `??` have similar meanings. Perhaps a threshold for centi-pawn difference between the chosen move and the engine's choice? Or a difference in winning chances?
* `!!` seems impossible to judge on score alone. Maybe it could be given to the engine's top choice, but very often that's just an obvious move, not a brilliancy.

In general you will have to iterate over the moves, [obtain scores](https://python-chess.readthedocs.io/en/latest/engine.html#analysing-and-evaluating-a-position), and look at their differences.

One of the example projects does something like that: https://github.com/rpdelaney-archive/python-chess-annotator. However it uses and outdated version of python-chess. It appears to be updated in the fork https://github.com/ddugovic/python-chess-annotator, but I am not sure about the status of that.

**Comment by PedanticHacker** [comment]
Computers are currently not evolved enough to distinguish between what is considered as good and what is considered as bad. That is something that only us humans can currently distinguish.

Those NAGs are just a way for us humans to denote a value of a chess move. When you look at those NAGs in some PGNs, those were manually inserted by a human.

Sorry, but that's just how it currently is.

**Comment by CoderAryanAnand** [comment]
Hi Niklas and Boštjan,
Thanks for your response. I looked at the repositories but still didn't find my answer.
Let's say that if the centipawn score goes down by 300, then it's a blunder(??). And if it goes down by 100 it's a mistake(?) and by 50 centipawns it's a dubious move(?!).
So right now the differences would be:
300 cp loss == Blunder(??)
100 cp loss == Mistake(?)
50 cp loss == Dubious move(?!)

So now I actually don't exactly know how to add these NAGs into the pgn. In python-chess-annotator, in the function [add_annotation,](https://github.com/rpdelaney-archive/python-chess-annotator/blob/master/annotator/__main__.py#L296) the program adds a NAG, but I don't understand how it does that. So now my main question is: How to add a NAG into the mainline of the pgn?

Thanks, Aryan

**Comment by niklasf** [comment]
Are you looking for `node.nags.add(chess.pgn.NAG_MISTAKE)`, where `node` is a `chess.pgn.GameNode`?

**Comment by CoderAryanAnand** [comment]
Is chess.pgn.GameNode not a variation?  I thought it was a variation that is why I didn't use it. But can it be used for a mainline too?

**Comment by niklasf** [comment]
Yes, the main variation is also a variation in this sense. `game.mainline()` iterates over the nodes (as in `chess.pgn.GameNode`) of the mainline.

**Comment by CoderAryanAnand** [comment]
Thank you very much. But I'm a little bit confused, so could you please provide me with an example?

**Comment by niklasf** [comment]
The following untested code marks every second move as a mistake:
```python
for i, node in enumerate(game.mainline()):
    if i % 2 == 1:
        node.nags.add(chess.pgn.NAG_MISTAKE)
```

**Comment by CoderAryanAnand** [comment]
Thank you very much! This answers my question. Have a nice day!
