### ISSUE TITLE
Find all possible previous moves

### ISSUE THREAD

**Issue by void4** [niklasf/python-chess#709]
Python-chess implements `board.generate_legal_moves()` - could another function, say `board.generate_previous_legal_moves()` be written that generates all possible legal moves that lead to the current board position?

**Comment by niklasf** [comment]
Retrograde analysis? I am sceptical, because it's a lot of work, especially when implementing it for all supported chess variants. It would probably also involve new types, because `chess.Move` would not carry enough information to then actually undo the move (even in Standard chess, but much less after an Atomic explosion).

What use case do you have in mind?

**Comment by void4** [comment]
Just for fun, I was wondering if there is an algorithm that gives one a possible move sequence from the initial position given a board position. Just found out that this is called https://en.wikipedia.org/wiki/Proof_game :)

Currently asking here: https://chess.stackexchange.com/questions/33328/given-a-legal-chess-position-is-there-an-algorithm-that-gets-a-series-of-moves

**Comment by niklasf** [comment]
I am gonna say it's out of scope for this library, but you got some nice answers on Stackexchange, including a few practical proof game solvers.
