### ISSUE TITLE
I want to know two things

### ISSUE THREAD

**Issue by Jishnu2010** [niklasf/python-chess#717]
First, how to flip the board? I have created a code with which I am using python's random module to choose a random valid move and give it on the board. Seems to work but only plays with white. So I play as black but the board doesn't flip so...

Second, how to convert uci to san and keep it as  a string in a variable? I would like to print this: White's last move: [Move e.g.] e4

The text in paranthesis is not to be printed

**Comment by lennertcl** [comment]
For flipping the svg, use `flipped=True`
```python
board = chess.Board()
chess.svg.board(board, flipped=True)
```
For the ASCII representation, I don't think it's built in but you can easily do it yourself:
```python
def flip(boardstr):
    l = boardstr.split("\n")
    reverse = "\n".join(l[::-1])
    return reverse
```
Converting a uci move to san is not possible because it depends on the state of the board. Possible solutions are: 

- Just print the uci move (`move.uci()`)
- Print the move that the user entered himself if the user entered a san representation 
- Construct the san representation from the move and the board using e.g. `str(board.piece_at(chess.E4))`

**Comment by niklasf** [comment]
Good answer. I'd suggest `board.san(move)` for the final point.

**Comment by lennertcl** [comment]
> Good answer. I'd suggest `board.san(move)` for the final point.

That is probably better. I did not know you could do that.

**Comment by Jishnu2010** [comment]
Thanks for your answers.

I use this for producing moves in SAN.

`board=chess.Board() # the board

legalmoves=list(board.legal_moves) #list of legal moves
	enginemove=random.choice(legalmoves) #a random choice
	producesan=board.variation_san([enginemove]) #the engine's move notation

print("Engine Move: {}".format(producesan))`
