### ISSUE TITLE
Question: how to get consistent scores from engine when comparing moves?

### ISSUE THREAD

**Issue by matteson** [niklasf/python-chess#741]
Awesome library, thanks!

I'm trying to iterate through positions in a PGN file and generate the difference in scores between the best move and the move made. In the following code, I'd expect only positive numbers to be printed (`infoBest['score']` strictly greater than `infoGame['score']`), but I find negative numbers pretty frequently.

I suspect I'm misunderstanding something. Could you point me in the right direction?

```
pgn = open(f'twic920.pgn')
    
game = chess.pgn.read_game(pgn)

engine = chess.engine.SimpleEngine.popen_uci('/usr/local/bin/stockfish')

board = game.board()
for move in game.mainline_moves():
    infoBest = engine.analyse(board, chess.engine.Limit(depth=18), game='best')
    infoGame = engine.analyse(board, chess.engine.Limit(depth=18), game='game', root_moves=[move])

    if board.turn:
        print(infoBest['score'].white().score() - infoGame['score'].white().score())
    else:
        print(infoBest['score'].black().score() - infoGame['score'].black().score())

    board.push(move)
```

**Comment by niklasf** [comment]
Hi, thanks!

Some small negative values are expected here. Engines aren't perfect, and restricting search to a particular move allows spending more time on that move. So the more focused analysis may find that the move in better than the original evaluation. Deeper search will reduce but never eliminate this effect.

Some advice:

* The if/else can be replaced with [`ìnfo["score"].pov(board.turn)`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore.pov).
* While iterating over the game, you're analysing many positions twice. You could just analyse the position, and compare the score to the score of the previous position.
* Analysing the game backwards (and not clearing the hashtable) improves analysis quality, because often the move from the game is a good hint.
* Comparing winning chances may be more meaningful than centi-pawn differences: https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Score.wdl.
* Your code will currently fail on mate scores.
