### ISSUE TITLE
Weight value for polyglot opening books goes up to 65520 instead of 65535

### ISSUE THREAD

**Issue by AttackingOrDefending** [niklasf/python-chess#748]
The weight value in polyglot opening books is uint16 (0 to 65535) but the maximum weight value I got when reading a polyglot opening book is 65520. Why doesn't the weight value go up to 65535?

**Comment by niklasf** [comment]
I see no reason why 65535 wouldn't work. Are you sure that the book really contains an entry of that magnitude? If so, can you please share the book?

**Comment by niklasf** [comment]
Ok, so I downloaded `Perfect2021.bin` from that source and did a hexdump, grepping for the starting position:

```
❯ hexdump Perfect2021.bin | grep "3b46 1896 9116 9cfc"
0005ef0 3b46 1896 9116 9cfc 1c03 f0ff 0000 0000
0005f00 3b46 1896 9116 9cfc db02 9099 0000 0000
0005f10 3b46 1896 9116 9cfc 9a02 3033 0000 0000
0005f20 3b46 1896 9116 9cfc 9501 3033 0000 0000
```

It has a weight column of f0ff, which is 65520 in little endian. So that's really the value that's stored in the file. So this would be a question for the creator of the file or Scid vs. PC.
