### ISSUE TITLE
"Engine sent invalid ponder move"

### ISSUE THREAD

**Issue by ulthiel** [niklasf/python-chess#751]
I think this issue was raised before but apparently without being resolved!? When analyzing a position using HIARCS I get the following error:

```
Engine: HIARCS 14 WCSC (Elo 2000)
DEBUG:chess.engine:<UciProtocol (pid=61043)>: << ucinewgame
DEBUG:chess.engine:<UciProtocol (pid=61043)>: << isready
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info string Position Learning OFF
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info string Ponder OFF
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info string Limit Strength ON
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info string UCI_Elo=2000
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> readyok
DEBUG:chess.engine:<UciProtocol (pid=61043)>: << position fen QN4n1/6r1/3k4/8/b2K4/8/8/8 b - - 0 1
DEBUG:chess.engine:<UciProtocol (pid=61043)>: << go infinite
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 1 seldepth 4 time 578 nodes 132 nps 398272 score cp -119 pv a4e8 a8d5 d6e7
nps 398272 nodes 132 depth 1 time 0.578s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 1 seldepth 4 time 767 nodes 181 nps 235 score cp -95 pv g7g4
nps 235 nodes 181 depth 1 time 0.767s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 1 seldepth 4 time 793 nodes 187 nps 235 score cp -40 pv g7g4 d4c3
nps 132914 nodes 187 depth 1 time 0.793s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 2 seldepth 4
nps 132914 nodes 187 depth 2 time 0.793s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 2 seldepth 5 time 881 nodes 208 nps 235 score cp -40 pv g7g4 d4c3
nps 235 nodes 208 depth 2 time 0.881s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info depth 3 seldepth 5
nps 235 nodes 208 depth 3 time 0.881s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info currmovenumber 1 currmove g7g4
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info nodes 312 nps 235
nps 235 nodes 312 depth 3 time 0.881s DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> info time 1347 nps 235 nodes 342 cpuload 0
DEBUG:chess.engine:<UciProtocol (pid=61043)>: >> bestmove g7g4  ponder d4c3
ERROR:chess.engine:Engine sent invalid ponder move
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/chess/engine.py", line 1761, in _parse_uci_bestmove
    ponder = board.parse_uci(tokens[2].lower())
  File "/usr/local/lib/python3.9/site-packages/chess/__init__.py", line 3032, in parse_uci
    move = Move.from_uci(uci)
  File "/usr/local/lib/python3.9/site-packages/chess/__init__.py", line 527, in from_uci
    promotion = PIECE_SYMBOLS.index(uci[4]) if len(uci) == 5 else None
ValueError: ' ' is not in list
```

I don't know what the problem is. Pondering is disabled, still HIARCS sends a ponder move. Does this cause the problem (if so, I think one could just ignore it). Moreover, HIARCS has *two* white spaces after the bestmove and before the keyword ponder. Does this cause an issue while parsing? The vary last line looks like that, I'm not sure though.

Also, one other thing. I noticed that some options are set automatically (UCI_AnalyseMode, Ponder, ...). I don't really like this because I want to have control over my options during analysis. Can I at least overwrite them? This is currently prevented.

**Comment by niklasf** [comment]
Hi. Which `import chess; print(chess.__version__)` are you running?

**Comment by ulthiel** [comment]
1.3.2. Ugh, there's a new one now. Let me check this.

**Comment by ulthiel** [comment]
No, same problem in 1.4.0.

**Comment by niklasf** [comment]
Thanks, that was just to exclude that as a possible cause.

I suspect that just like there's a trailing space behind the bestmove, there's also a trailing space behind ponder, tripping up the parser. Fixed on latest master. You can try it before the next release using

```
pip install git+https://github.com/niklasf/python-chess.git
```

---

As for the other points: It's normal that UCI engines send `bestmove ... ponder` even if ponder is disabled. That's just a suggestion for a move that *could* be pondered.

You get control over all options, but to make the offered abstractions work, some options require special handling by the `chess.engine` module.

* For `UCI_AnalyseMode`, the default is off for `.play()`  and on for `.analyse()`/`.analysis()`. That seems sensible to me. It can be overwritten by explicitly setting the option.
* Pondering is off by default, and can be enabled using `.play(..., ponder=True)`. The module needs to manage this, because it impacts the flow of communication.
* MultiPV needs to be set using `.analyse(..., multipv=...)`, because it impacts the type of the returned info data (single entry vs list).
* `UCI_Chess960` and `UCI_Variant` are managed, because they are implied by the type of `chess.Board` (which needs to be able to interpret the lines generated by the engine).

**Comment by ulthiel** [comment]
Excellent, this works now! Thanks.
