### ISSUE TITLE
Incorrect FEN & EPD concerning en_passant square

### ISSUE THREAD

**Issue by m-f-h** [niklasf/python-chess#834]
The standard clearly specifies that the "en passant square" in FEN and EPD is the square "behind the pawn" that was pushed by two ranks, regardless of whether there is a pawn in position to make an en passant capture.
See for example https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation#Definition point 4, and #Examples ("after move 1.e4"), and cited references including the original and revised specs.

I think that the currently distributed version does this wrong: If I understand correctly, it means that
```
>>> B = chess.Board(); B.push_san("d4"); B.fen()
```
should give
```
"rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1"
```
but the actual output (in `chess.__version__() == "1.7.0"`, just installed via `pip install chess`), has a "-" instead of "d3". I didn't (yet) dig into the code, but I suspect you check whether there's a pseudolegal ep capture.

EDIT: Not a bug, but a feature!(??): https://github.com/niklasf/python-chess/blob/67a7e00ecd5bc64c8942a938222b28fb8265f4a8/chess/__init__.py#L2373-L2376

**Comment by m-f-h** [comment]
Ah, now I found that the problem is in the default _EnPassantSpec = "legal" in Board.fen() and Board.epd() - the default should be to follow the specification! Why would you choose 
> "By default, only fullly legal...are included, pass ``fen`` to strictly follow the FEN specification"

The default should be to follow the specification, not something else -- that's a weird default... :-(

**Comment by niklasf** [comment]
Yeah, sorry, this is a bit controversial. In my oppinion the specification is overstepping by mandating software to provide information that is not really part of the position. It just happens to be implemented in such a way that doing so is actually possible.

I took this liberty, because X-FEN (also a widely accepted specification and one of the available options) already shows that omitting impossible en passant squares is a broadly compatible change.

Did this cause any real issue in your use case, or were you "just" surprised by the output?
