### ISSUE TITLE
Most efficient evaluation of all legal moves at multiple depths

### ISSUE THREAD

**Issue by singerep** [niklasf/python-chess#857]
Hi,

I am curious what the most efficient approach would be to evaluate all legal moves in a given position. Interestingly, looping through all legal moves and evaluating the resulting position at depth n-1 is giving me faster speeds than using the multipv parameter at depth n (it is also faster when both are at depth n, but I am under the impression that the former strategy would be searching further?) -- not sure if I am doing something wrong or not, as I see this is contradictory to something you said in the [community chat](https://gitter.im/python-chess/community?at=5fd3d35b91e8cb3e8cf62482).

Also, what is the most efficient way to evaluate a move at multiple depths? Right now I just evaluate at 3 and then 5 and then 10, for example, but wondering if there is a potential boost here too. Seems silly, I know, but is useful for some research I am working on.

Thanks in advance,
Ethan

**Comment by niklasf** [comment]
Hi Ethan,

if you need evaluations for *all* legal moves, not just a limited number of top legal moves like in the chat, multipv can not offer much of an improvement over manual iteration. Basically the only difference would be if it uses the hashtable more or less efficiently. I don't know which it is.

Note that a fair comparison would be `go searchmoves <move> ... depth <n>` (`root_moves` argument in python-chess) for each move vs. multipv with depth n. (Due to pruning, playing a move and analysing with depth `n-1` is not the same as analyzing the previous position with depth `n`.)

As for efficiently searching multiple depths, you can do it slightly more efficiently in a single search. See how https://python-chess.readthedocs.io/en/latest/engine.html#indefinite-or-infinite-analysis iterates over each line of info coming from the engine. You can do this and record the last evaluation of each depth.
