### ISSUE TITLE
Pgn parsing: extract all variations as list of moves

### ISSUE THREAD

**Issue by Kraymer** [niklasf/python-chess#869]
This is not an issue or a feature request but a question regarding how to use the library.

Given a pgn file, what is the straightest way to obtain a list of all possible lines ?

For example with this content 

> 1. e4 ( 1. d4 d5 ) ( 1. a4 ) 1... e5

how to get 

~~~~
[
    ["e4", "e5"],
    ["d4", "d5"],
    ["a4"]
]
~~~~

I'm considering using a `BaseVisitor` and writing code in `visit_move`, `begin_variation` and `end_variation` to alter a global data structure but am wondering if there is a better way to proceed.

**Comment by niklasf** [comment]
Yeah, that seems like the right approach. I don't think there's anything super straight-forward to go from tree-like PGNs to such a flat structure.

If you aren't already, make sure to use `chess.pgn.read_game(pgn, Visitor=YourVisitor)` instead of `chess.pgn.read_game(pgn).accept(YourVisitor())`, to cut out the intermediate game representation.
