### ISSUE TITLE
Issue with a draw

### ISSUE THREAD

**Issue by pavolkacej** [niklasf/python-chess#871]
If I play following moves on the board:

```
1. g4 d5 2. e3 h6 3. Qe2 Nf6 4. h3 b6 5. f3 Ba6 6. Qd1 Rg8 7. f4 Bxf1 8. Kxf1 Qc8 9. f5 Nc6 10. Qe1 h5 11. Ne2 hxg4 12. Kg2 gxh3+ 13. Rxh3 Qxf5 14. Rg3 Nh5 15. Nec3 Nxg3 16. Kxg3 a6 17. Kh4 Ne5 18. Qd1 Rh8+ 19. Kg3 c6 20. b4 Rg8 21. Kh2 f6 22. Na3 Rb8 23. Kh1 Rb7 24. Qe2 b5 25. Kg1 e6 26. d4 Qg6+ 27. Kf1 Bxb4 28. dxe5 Bxc3 29. Rb1 a5 30. Qd3 Qxd3+ 31. cxd3 Rf8 32. exf6 e5 33. f7+ Rbxf7+ 34. Ke2 Rf6 35. Rb3 b4 36. Rxc3 bxc3 37. e4 dxe4 38. dxe4 g6 39. Be3 g5 40. Nc4 Rh8 41. a3 a4 42. Bxg5 Re6 43. Kf3 Kf8 44. Nb6 c2 45. Bc1 Rf6+ 46. Kg3 Rg8+ 47. Kh2 Rh8+ 48. Kg2 Rg6+ 49. Kf2 Rh2+ 50. Kf3 Rh3+ 51. Kf2 Rh2+ 52. Kf1 Rh1+ 53. Kf2
```

and call 
```print( board.result(claim_draw=True) )```
it says "1/2-1/2"

I don't understand this, since this position is not already repeated 3 times, also 50 rules move is not applicable. I have verified this on chess.com

Could you please take a look if you can reproduce this?

Thank you

**Comment by pavolkacej** [comment]
Save the moves to game.pgn

Reproduce the issue by running:

`import chess.pgn
if __name__ == "__main__":
    pgn = open("game.pgn")
    first_game = chess.pgn.read_game(pgn)
    board = first_game.board()
    for move in first_game.mainline_moves():
        board.push(move)
        print(chess.Board().variation_san(board.move_stack))
        print(board.result(claim_draw=True))
       `

**Comment by pavolkacej** [comment]
Looking at this pgn, white is not able to offer a draw "prematurely" as it could in the previous example

```
1. e4 e6 2. d4 Bd6 3. e5 Bf8 4. Nf3 Nh6 5. Bxh6 gxh6 6. Bd3 d6 7. exd6 c6 8. O-O b6 9. c4 Qxd6 10. Nc3 a6 11. Qe2 Bd7 12. Qe5 Qxe5 13. Nxe5 Bg7 14. Ne4 O-O 15. Nd6 a5 16. f4 b5 17. c5 Bc8 18. Rf3 f6 19. Ng4 Rd8 20. Rg3 Kf8 21. Nxc8 Rxc8 22. Bxh7 f5 23. Ne5 h5 24. h4 Rc7 25. Bg6 Rc8 26. Bxh5 Bf6 27. Ng6+ Ke8 28. Ne5+ Kf8 29. Ng6+ Ke8 30. Ne5+
```

**Comment by pavolkacej** [comment]
@Disservin okay, but then why in the second game, white is unable to claim a draw after `29. Ng6+ Ke8` ?

**Comment by sshivaji** [comment]
Just talking about this with a former tournament chess master/player
perspective. You CAN offer a draw after 30. Ne5+, however, you cannot force
it, it's not the first time you can offer a draw, you can offer a draw
anytime you want even before that.  Before 30.. Ke8, black can force a draw
with a claim.

Don't worry about the confusion, so many tournament players have made
incorrect 3 fold repetition claims, even I messed up in a tournament game,
and my opponent was able to claim a draw. It's also somewhat "annoying" to
call a tournament director to validate a claim, it's easier in practice to
just agree with your opponent instead of an official claim. The only
warning is that if you want to repeat the position twice to test your
opponent, it's important to make sure it's twice and not three times :)
