### ISSUE TITLE
Not possible to know when the search is done when using an engine in "poll" mode.

### ISSUE THREAD

**Issue by mooskagh** [niklasf/python-chess#889]
I'm trying to convert an old program that used `chess.uci` to use new python-chess api.

The old version looked like this:
```python
x = chess.uci.popen_engine('./sf')
x.info_handlers.append(info_appender)
x.go(async_callback=True, time=3)

while not x.done():
    # Do other stuff
```

However, I cannot find anything similar to `x.done()` in the new API.

```python
#!/usr/bin/env python3

import chess
import chess.engine
import time

engine = chess.engine.SimpleEngine.popen_uci("/usr/bin/stockfish")

with engine.analysis(chess.Board(),
                     limit=chess.engine.Limit(time=10)) as analysis:
    while True:
        while not analysis.empty():
            info = analysis.get()
            print(info)
        print("Doing other stuff")
        time.sleep(1)
```
I cannot find a way to know that the search is over from within the loop.
The only way to know that is to call `analysis.get()` which would throw an exception if the search is done, but it will block if the search is not done, but there's no outstanding infos to get, that's not what I need.

**Comment by mooskagh** [comment]
Ended up using `analysis.inner._finished.done()` check.
Looks a bit hacky, but works.

**Comment by niklasf** [comment]
The intended/recommended way is to use a for loop:

```python
with engine.analysis(chess.Board(), limit=chess.engine.Limit(time=10)) as analysis:
    for info in analysis:
        print(info)
```

The loop terminates after the analysis is complete and all info has been consumed. There is no need to manually sleep. The loop will already block until more data is available, and any additional sleep would just stall the thread while the engine pushes more info regardless.

**Comment by mooskagh** [comment]
The sleep was just to demonstrate that "something else is being done".

Actually, I poll the chess engine inside the GUI (well, TUI) loop, and I'd prefer GUI loop to be the outer loop rather than python-chess loop.

![image](https://user-images.githubusercontent.com/11266455/172065724-227dd572-bd87-48ec-a4b6-36822bd99959.png)

**Comment by niklasf** [comment]
Ah, I see. Looks cool, btw.

Mixing the event loops is a bit dubious, because properly waiting for an engine event could block the GUI and vice versa, so you can never really block anywhere. Cleanest would be to give the engine its own thread or use asyncio. Maybe your chosen TUI lib supports asyncio as well?

That said, `analysis.inner._finished.done()` is fine, with a few caveats:
* You should check one more time if any items remain in the queue.
* If any exception came up during search, it will not see the light of day if the underlying future is checked for completion but never awaited. Might be acceptable.
* There's no stability guarantee for `_finished` across python-chess versions. I'll consider adding an equivalent public API.

**Comment by niklasf** [comment]
How about a new method [`AnalysisResult.would_block()`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.AnalysisResult.would_block)? Instead of exposing `finished` which is easy to misuse as described above, this would encourage still calling `get()`, `next()`, or `wait()`, so that completion including any exceptions can be observed.

**Comment by mooskagh** [comment]
Yeah that's great!
I actually initially hoped that `empty()` would return `False` if the search is over, and now `would_block()` does exactly that.

**Comment by mooskagh** [comment]
I think the documentation for the function is not entirely correct though.  
When thinking is in progress but there are pendint `info`s to fetch, `would_block()` will return False, but `wait()` will still block as it only waits for the thinking to complete and doesn't return on intermediate `info`s.

**Comment by niklasf** [comment]
Ah, yes, thanks for catching this. Will fix the docs.
