### ISSUE TITLE
the chess.svg module doesn't seem to be working right

### ISSUE THREAD

**Issue by phonokoye** [niklasf/python-chess#903]
Based on the documentation for python-chess 1.8.0 found [here](https://python-chess.readthedocs.io/en/v1.8.0/svg.html) on the chess.svg module, the code below is supposed to produce this [picture](https://python-chess.readthedocs.io/en/v1.8.0/_images/Ne4.svg)
on a pygame surface

```python
import chess
import chess.svg

import pygame, sys, io
pygame.init()

board = chess.Board("8/8/8/8/4N3/8/8/8 w - - 0 1")
squares = board.attacks(chess.E4)
text = chess.svg.board(board, squares=squares, size=400)

byts = bytes(text, encoding='utf-8')
fileobj = io.BytesIO(byts)
surf = pygame.image.load(fileobj)

win = pygame.display.set_mode((400, 400))
win.blit(surf, (0, 0))

while True:
    pygame.display.update()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
```
`
but when I run it, i see an empty board, 
![Screenshot 2022-06-28 183743](https://user-images.githubusercontent.com/78999501/176248766-3a4c6c71-d664-45f2-a012-6019140a0b9e.jpg)

did i miss something in the documentation or is there a mistake in the module.

**Comment by niklasf** [comment]
Neither :)

Unfortunately pygame only partially supports the SVG Tiny spec: https://www.pygame.org/docs/ref/image.html says "SVG (limited support, using Nano SVG)".

If you want to stick with `chess.svg` you'd have to [use a different library to render the SVG](https://stackoverflow.com/a/64598021/722291) and then render that image, instead of using pygame directly.
