### ISSUE TITLE
Crazyhouse FENs incompatible with Lichess

### ISSUE THREAD

**Issue by Torom** [niklasf/python-chess#913]
I noticed that the crazyhouse FENs from python-chess are unfortunately not compatible with those from Lichess:

python-chess
```
rnbqkbnr/ppp1pppp/8/3P4/8/8/PPPP1PPP/RNBQKBNR[P] b KQkq - 0 2
```
Lichess
```
rnbqkbnr/ppp1pppp/8/3P4/8/8/PPPP1PPP/RNBQKBNR/P b KQkq - 0 2
```

Unfortunately, this leads to the fact that you cannot pass the FENs to the `/api/cloud-eval` endpoint at Lichess, for example, without conversion.
I think it would be very nice if either Lichess could support this FEN format or python-chess could output a compatible FEN using a parameter of `VariantBoard.fen()` or so.

**Comment by niklasf** [comment]
Whenever Lichess parses FENs it accepts both formats, and there are (stalled out plans) to switch to `[...]` at https://github.com/lichess-org/lila/issues/2435.

Unfortunately, just supporting both output formats in python-chess will not help, because the order of the pieces in the pocket is different on Lichess, depending on move order. The way to go would be Lichess API parsing and normalizing FENs, like it does everywhere else.
