### ISSUE TITLE
syzygy probing code

### ISSUE THREAD

**Issue by piccoloprogrammatore** [niklasf/python-chess#93]
With the following code I get an index error

import chess.syzygy

tablebases = chess.syzygy.open_tablebases("./syzygy")

board = chess.Board("4r1K1/6PP/3k4/8/8/8/8/8 w - - 1 64")
print tablebases.probe_dtz(board) 
print tablebases.probe_wdl(board)
tablebases.close()

**Comment by niklasf** [comment]
Hi, thanks for reporting. I'll check this out asap. Meanwhile: Can you please provide the full stacktrace/output? That might be useful.

**Comment by niklasf** [comment]
Reproduced, fixed, v0.15.1 with the bugfix released.

A while ago I set a 100$ bug bounty for critical issues in the core module. Since this was actually a move generation bug that I carelessly introduced in the v0.15.0 release you can claim it, if you want. Send me a mail at niklas.fiekas@backscattering.de. (Alternatively I am more than happy to donate the bounty to a good cause, for example to support development of the open source chess site https://lichess.org)
