### ISSUE TITLE
Read evaluations and clock timers

### ISSUE THREAD

**Issue by quentindeltour** [niklasf/python-chess#990]
Hi,

I am trying to use your package to extract data from the ongoing World Championship to python. 

I used a PGN export of all games that I found on lichess (you can find it [here](https://lichess.org/api/broadcast/lrdHUzyS.pgn))

Then I used the following code from the documentation to extract it : 

```
import chess
import chess.pgn
with open(PATH_TO_PGN, encoding="utf-8") as pgn:
    first_game = chess.pgn.read_game(pgn)
```

And it works fine for extracting the moves of the game, for example : 
`first_game.mainline_moves()`

But then, if I want to extract computer evaluation or clock timers, I don't get anything : 
```
first_game.eval()
first_game.clock()
```

Both result in None sent by the console. 

I have checked the PGN file, and it contains both informations (for example : 1. e4 { [%eval 0.36] [%clk 1:59:53] })

**Comment by TheMostVexingParse** [comment]
You can get the evaluation and clock data from child nodes.

~~~
>>> first_game.eval()
>>> #Nothing happens
>>> 
>>> first_game.next()
<ChildNode at 0x2339b5e50f0 (1. e4 ...)>
>>> 
>>> first_game.next().eval()
PovScore(Cp(-36), BLACK)
>>> 
>>> first_game.next().clock()
7193.0
>>>
~~~

To get the next node:
~~~
>>> first_game.next().next()
<ChildNode at 0x2339b602e10 (1... e5 ...)>
>>>
>>> first_game.next().next().eval()
PovScore(Cp(+35), WHITE)
>>>
~~~


Since I haven't used that library in a year ,there may be native way to retrieve the move with move number that I am not aware of, but if there isn't, you can use something like this:

~~~
>>> def get_node(game, move):
	for i in range(move):
		game = game.next()
	return game

>>> get_node(first_game, 1)
<ChildNode at 0x2339b5e50f0 (1. e4 ...)>
>>> get_node(first_game, 2)
<ChildNode at 0x2339b602e10 (1... e5 ...)>
>>> get_node(first_game, 1).eval()
PovScore(Cp(-36), BLACK)
~~~

**Comment by niklasf** [comment]
And if the nodes are needed in order: [`for node in first_game.mainline(): ...`](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameNode.mainline)
